apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dev
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-dev
  template:
    metadata:
      labels:
        app: nginx-dev
    spec:
      nodeName: k8s-worker
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: configs
          configMap:
            name: nginx-global
      containers:
        - name: nginx-container
          image: nginx
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
            - name: configs
              mountPath: /etc/configs
              readOnly: true
          envFrom:
            - configMapRef:
                name: nginx-dev
        - name: debian-container
          image: debian
          volumeMounts:
            - name: shared-data
              mountPath: /pod-data
          command: ["/bin/sh"]
          args: ["-c", "Debian says Hello! > /pod-data/index.html"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
  labels:
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      nodeName: k8s-worker2
      volumes:
        - name: webdata
          persistentVolumeClaim:
            claimName: nginx-pvc10mi
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - name: http-server
              containerPort: 80
          volumeMounts:
            - name: webdata
              mountPath: /usr/share/nginx/html
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: nginx-global
                  key: APP_NAME
            - name: APP_OWNER
              valueFrom:
                configMapKeyRef:
                  name: nginx-global
                  key: APP_OWNER
            - name: APP_DESCRIPTION
              valueFrom:
                configMapKeyRef:
                  name: nginx-global
                  key: APP_DESCRIPTION
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: nginx-prod
                  key: ENV
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: nginx-conf-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nginx-conf-secret
                  key: password
          command: ["/bin/echo", "From $(APP_OWNER), the $(APP_NAME) owner: $(APP_DESCRIPTION)! My username is $(USERNAME), my password is $(PASSWORD)"]