apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv10m
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data